version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

brews:
  - name: bump
    url_template: "https://github.com/flaticols/bump/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Denis Panfilov
      email: gh@flaticols.dev
    directory: Formula
    homepage: "https://bump.flaticols.dev"
    description: "Bump semver git tag in yours repository"
    license: "MIT"
    skip_upload: auto
    repository:
      owner: flaticols
      name: homebrew-apps
      branch: main

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
